# Generated by Django 5.2.9 on 2026-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="monitor",
            table_comment="服务器性能监控记录表",
        ),
        migrations.AlterField(
            model_name="monitor",
            name="boot_time",
            field=models.FloatField(
                db_comment="系统启动时间", default=0, verbose_name="Boot Time"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="cpu_load",
            field=models.FloatField(
                db_comment="CPU负载", default=0, verbose_name="CPU Load"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="cpu_percent",
            field=models.FloatField(
                db_comment="CPU使用率", default=0, verbose_name="CPU Percent"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="记录创建时间",
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="disk_used",
            field=models.FloatField(
                db_comment="已用磁盘", default=0, verbose_name="Disk Used"
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="memory_used",
            field=models.FloatField(db_comment="已用内存", verbose_name="Memory Used"),
        ),
    ]
