# Generated by Django 5.2.9 on 2026-07-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0002_alter_monitor_table_comment_alter_monitor_boot_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="monitor",
            name="boot_time",
            field=models.FloatField(
                db_comment="系统启动时间",
                default=0,
                help_text="System boot timestamp (Unix epoch seconds)",
                verbose_name="Boot Time",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="cpu_load",
            field=models.FloatField(
                db_comment="CPU负载",
                default=0,
                help_text="System CPU load average (1-minute)",
                verbose_name="CPU Load",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="cpu_percent",
            field=models.FloatField(
                db_comment="CPU使用率",
                default=0,
                help_text="Overall CPU utilization percentage",
                verbose_name="CPU Percent",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="记录创建时间",
                help_text="Timestamp when this monitoring record was collected",
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="disk_used",
            field=models.FloatField(
                db_comment="已用磁盘",
                default=0,
                help_text="Amount of disk space currently in use (bytes)",
                verbose_name="Disk Used",
            ),
        ),
        migrations.AlterField(
            model_name="monitor",
            name="memory_used",
            field=models.FloatField(
                db_comment="已用内存",
                help_text="Amount of physical memory currently in use (bytes)",
                verbose_name="Memory Used",
            ),
        ),
    ]
