# Generated by Django 5.2.9 on 2026-07-14 10:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0002_initial"),
        ("system", "0004_alter_datapermission_table_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="setting",
            table_comment="系统设置表，存储各类配置项的名称、值及加密状态",
        ),
        migrations.AlterField(
            model_name="setting",
            name="category",
            field=models.CharField(
                db_comment="设置项分类",
                default="default",
                max_length=128,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="encrypted",
            field=models.BooleanField(
                db_comment="是否加密存储", default=False, verbose_name="Encrypted"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="id",
            field=models.UUIDField(
                db_comment="主键ID（UUID）",
                default=uuid.uuid4,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="is_active",
            field=models.BooleanField(
                db_comment="是否启用", default=True, verbose_name="Is active"
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="name",
            field=models.CharField(
                db_comment="设置项名称",
                max_length=128,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.TextField(
                blank=True, db_comment="设置项值", null=True, verbose_name="Value"
            ),
        ),
    ]
