# Generated by Django 5.2.9 on 2026-07-14 10:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "settings",
            "0003_alter_setting_table_comment_alter_setting_category_and_more",
        ),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="setting",
            name="category",
            field=models.CharField(
                db_comment="设置项分类",
                default="default",
                help_text="Configuration category for grouping settings",
                max_length=128,
                verbose_name="Category",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                help_text="Timestamp automatically set when the record is first created",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                help_text="User who created this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                help_text="Department to which this record belongs, used for data-level permission filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                help_text="Optional brief description or remark for this record",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="encrypted",
            field=models.BooleanField(
                db_comment="是否加密存储",
                default=False,
                help_text="Whether the value is encrypted at rest",
                verbose_name="Encrypted",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="id",
            field=models.UUIDField(
                db_comment="主键ID（UUID）",
                default=uuid.uuid4,
                help_text="Auto-generated UUID primary key",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="is_active",
            field=models.BooleanField(
                db_comment="是否启用",
                default=True,
                help_text="Whether this setting is active and loaded into the system",
                verbose_name="Is active",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="name",
            field=models.CharField(
                db_comment="设置项名称",
                help_text="Unique configuration item name",
                max_length=128,
                unique=True,
                verbose_name="Name",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                help_text="Timestamp automatically updated each time the record is saved",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="setting",
            name="value",
            field=models.TextField(
                blank=True,
                db_comment="设置项值",
                help_text="Configuration value, supports JSON format",
                null=True,
                verbose_name="Value",
            ),
        ),
    ]
