# Generated by Django 5.2.9 on 2026-07-14 10:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_initial"),
        ("system", "0004_alter_datapermission_table_comment_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="messagecontent",
            table_comment="消息内容表，存储通知消息内容及关联的用户、部门、角色",
        ),
        migrations.AlterModelTableComment(
            name="messageuserread",
            table_comment="用户消息已读记录表，记录用户对消息的已读状态",
        ),
        migrations.AlterModelTableComment(
            name="systemmsgsubscription",
            table_comment="系统消息订阅表，记录系统级消息类型及接收用户集合",
        ),
        migrations.AlterModelTableComment(
            name="usermsgsubscription",
            table_comment="用户消息订阅表，记录用户对各类消息的接收后端偏好",
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="extra_json",
            field=models.JSONField(
                blank=True,
                db_comment="附加JSON数据",
                null=True,
                verbose_name="Additional json data",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="level",
            field=models.CharField(
                choices=[
                    ("info", "Ordinary notices"),
                    ("primary", "General notices"),
                    ("success", "Success notices"),
                    ("danger", "Important notices"),
                ],
                db_comment="通知级别（info/primary/success/danger）",
                default="info",
                max_length=20,
                verbose_name="Notice level",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="message",
            field=models.TextField(
                blank=True,
                db_comment="通知消息内容",
                null=True,
                verbose_name="Notice message",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="notice_type",
            field=models.SmallIntegerField(
                choices=[
                    (0, "System notification"),
                    (1, "System announcement"),
                    (2, "User notification"),
                    (3, "Department notification"),
                    (4, "Role notification"),
                ],
                db_comment="通知类型（0-系统 1-公告 2-用户 3-部门 4-角色）",
                default=2,
                verbose_name="Notice type",
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="publish",
            field=models.BooleanField(
                db_comment="是否发布", default=True, verbose_name="Publish"
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="title",
            field=models.CharField(
                db_comment="通知标题", max_length=255, verbose_name="Notice title"
            ),
        ),
        migrations.AlterField(
            model_name="messagecontent",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="notice",
            field=models.ForeignKey(
                db_comment="关联的消息内容",
                on_delete=django.db.models.deletion.CASCADE,
                to="notifications.messagecontent",
                verbose_name="Notice",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="owner",
            field=models.ForeignKey(
                db_comment="消息所属用户",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="unread",
            field=models.BooleanField(
                db_comment="是否未读",
                db_index=True,
                default=True,
                verbose_name="Unread",
            ),
        ),
        migrations.AlterField(
            model_name="messageuserread",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="message_type",
            field=models.CharField(
                db_comment="系统消息类型",
                max_length=128,
                unique=True,
                verbose_name="message type",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="receive_backends",
            field=models.JSONField(
                db_comment="消息接收后端列表",
                default=list,
                verbose_name="receive backend",
            ),
        ),
        migrations.AlterField(
            model_name="systemmsgsubscription",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="message_type",
            field=models.CharField(
                db_comment="消息类型", max_length=128, verbose_name="message type"
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="receive_backends",
            field=models.JSONField(
                db_comment="消息接收后端列表",
                default=list,
                verbose_name="receive backend",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="usermsgsubscription",
            name="user",
            field=models.ForeignKey(
                db_comment="订阅用户",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_msg_subscription",
                to=settings.AUTH_USER_MODEL,
                verbose_name="User",
            ),
        ),
    ]
