# Generated by Django 5.2.9 on 2026-07-15 03:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="公司全称，唯一标识一个公司主体",
                        help_text="公司全称，用于唯一标识一个公司主体",
                        max_length=128,
                        unique=True,
                        verbose_name="公司名称",
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        blank=True,
                        db_comment="公司简称，方便列表展示",
                        help_text="公司简称，方便列表展示",
                        max_length=64,
                        null=True,
                        verbose_name="简称",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="公司是否启用",
                        default=True,
                        help_text="公司是否启用，启用后可在业务中使用",
                        verbose_name="启用状态",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "公司主体",
                "verbose_name_plural": "公司主体",
                "db_table_comment": "公司主体表，记录企业/组织的基本信息",
                "ordering": ["name"],
            },
        ),
    ]
