# Generated by Django 5.2.9 on 2026-07-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_init"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="company",
            table_comment="公司主体表，记录企业/组织的基本信息",
        ),
        migrations.AlterField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(
                db_comment="公司是否启用",
                default=True,
                help_text="公司是否启用，启用后可在业务中使用",
                verbose_name="启用状态",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="name",
            field=models.CharField(
                db_comment="公司全称，唯一标识一个公司主体",
                help_text="公司全称，用于唯一标识一个公司主体",
                max_length=128,
                unique=True,
                verbose_name="公司名称",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="short_name",
            field=models.CharField(
                blank=True,
                db_comment="公司简称，方便列表展示",
                help_text="公司简称，方便列表展示",
                max_length=64,
                null=True,
                verbose_name="简称",
            ),
        ),
    ]
