# Generated by Django 5.2.9 on 2026-07-15 06:05

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields.encrypted


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="company",
            table_comment="公司主体表，记录企业/组织的工商登记信息、证照文件及联系方式",
        ),
        migrations.AddField(
            model_name="company",
            name="business_license",
            field=models.ForeignKey(
                blank=True,
                db_comment="营业执照扫描件或照片（关联UploadFile）",
                help_text="公司营业执照扫描件或照片",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_business_license",
                to="system.uploadfile",
                verbose_name="营业执照",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="business_scope",
            field=models.TextField(
                blank=True,
                db_comment="经营范围描述",
                help_text="营业执照上登记的经营范围",
                null=True,
                verbose_name="经营范围",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="company_type",
            field=models.CharField(
                choices=[
                    ("limited_liability", "有限责任公司"),
                    ("joint_stock", "股份有限公司"),
                    ("sole_proprietorship", "个人独资企业"),
                    ("partnership", "合伙企业"),
                    ("individual_business", "个体工商户"),
                    ("other", "其他"),
                ],
                db_comment="公司类型枚举值",
                default="limited_liability",
                help_text="公司类型：有限责任公司/股份有限公司/个人独资企业/合伙企业/个体工商户/其他",
                max_length=32,
                verbose_name="公司类型",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="establishment_date",
            field=models.DateField(
                blank=True,
                db_comment="公司成立日期",
                help_text="营业执照上登记的成立日期",
                null=True,
                verbose_name="成立日期",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_representative",
            field=models.CharField(
                blank=True,
                db_comment="法定代表人姓名",
                help_text="公司法定代表人姓名",
                max_length=64,
                null=True,
                verbose_name="法定代表人",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_representative_contact",
            field=apps.common.fields.encrypted.EncryptedTextField(
                blank=True,
                db_comment="法定代表人联系方式（加密存储）",
                default="",
                help_text="法定代表人联系电话或其他联系方式（加密存储）",
                null=True,
                verbose_name="法人联系方式",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_representative_id_back",
            field=models.ForeignKey(
                blank=True,
                db_comment="法定代表人身份证反面照片（关联UploadFile）",
                help_text="法定代表人身份证反面照片",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_id_back",
                to="system.uploadfile",
                verbose_name="法人身份证反面",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="legal_representative_id_front",
            field=models.ForeignKey(
                blank=True,
                db_comment="法定代表人身份证正面照片（关联UploadFile）",
                help_text="法定代表人身份证正面照片",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_id_front",
                to="system.uploadfile",
                verbose_name="法人身份证正面",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registered_address",
            field=models.CharField(
                blank=True,
                db_comment="公司注册地址（住所）",
                help_text="营业执照上登记的住所/注册地址",
                max_length=256,
                null=True,
                verbose_name="住所",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="registered_capital",
            field=models.CharField(
                blank=True,
                db_comment="注册资本及币种",
                help_text='注册资本，含币种信息，如"100万元人民币"',
                max_length=64,
                null=True,
                verbose_name="注册资本",
            ),
        ),
        migrations.AddField(
            model_name="company",
            name="unified_social_credit_code",
            field=models.CharField(
                blank=True,
                db_comment="统一社会信用代码，18位",
                help_text="18位统一社会信用代码，营业执照上登记的唯一代码",
                max_length=18,
                null=True,
                unique=True,
                verbose_name="统一社会信用代码",
            ),
        ),
    ]
