# Generated by Django 5.2.9 on 2026-07-15 06:30

import apps.common.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_add_company_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="business_license",
            field=models.FileField(
                blank=True,
                db_comment="营业执照扫描件或照片",
                help_text="公司营业执照扫描件或照片",
                null=True,
                upload_to=apps.common.core.models.upload_directory_path,
                verbose_name="营业执照",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_representative_id_back",
            field=models.FileField(
                blank=True,
                db_comment="法定代表人身份证反面照片",
                help_text="法定代表人身份证反面照片",
                null=True,
                upload_to=apps.common.core.models.upload_directory_path,
                verbose_name="法人身份证反面",
            ),
        ),
        migrations.AlterField(
            model_name="company",
            name="legal_representative_id_front",
            field=models.FileField(
                blank=True,
                db_comment="法定代表人身份证正面照片",
                help_text="法定代表人身份证正面照片",
                null=True,
                upload_to=apps.common.core.models.upload_directory_path,
                verbose_name="法人身份证正面",
            ),
        ),
    ]
