# Generated by Django 5.2.9 on 2026-07-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captcha", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="captchastore",
            table_comment="验证码存储表，保存验证码的挑战、响应及过期时间",
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="challenge",
            field=models.CharField(db_comment="验证码挑战值", max_length=32),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="expiration",
            field=models.DateTimeField(db_comment="验证码过期时间"),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="hashkey",
            field=models.CharField(
                db_comment="验证码唯一哈希键", max_length=40, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="id",
            field=models.AutoField(
                db_comment="主键ID", primary_key=True, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="response",
            field=models.CharField(db_comment="验证码响应值", max_length=32),
        ),
    ]
