# Generated by Django 5.2.9 on 2026-07-14 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("captcha", "0002_alter_captchastore_table_comment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="captchastore",
            name="challenge",
            field=models.CharField(
                db_comment="验证码挑战值",
                help_text="Challenge value generated by the captcha system",
                max_length=32,
                verbose_name="Challenge",
            ),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="expiration",
            field=models.DateTimeField(
                db_comment="验证码过期时间",
                help_text="Expiration time after which the captcha is automatically invalidated",
                verbose_name="Expiration",
            ),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="hashkey",
            field=models.CharField(
                db_comment="验证码唯一哈希键",
                help_text="Unique SHA-1 hash key used to identify and look up the captcha record",
                max_length=40,
                unique=True,
                verbose_name="Hash key",
            ),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="id",
            field=models.AutoField(
                db_comment="主键ID",
                help_text="Auto-incremented primary key",
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="captchastore",
            name="response",
            field=models.CharField(
                db_comment="验证码响应值",
                help_text="Expected response value that the user needs to input",
                max_length=32,
                verbose_name="Response",
            ),
        ),
    ]
