# Generated by Django 5.2.9 on 2026-07-15 03:35

import apps.common.fields.encrypted
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CloudPlatform",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        db_comment="平台实例名称，唯一",
                        help_text="自定义平台实例名称，如：生产环境-腾讯云",
                        max_length=128,
                        unique=True,
                        verbose_name="平台名称",
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("tencent", "腾讯云"),
                            ("aliyun", "阿里云"),
                            ("aws", "AWS"),
                            ("azure", "Azure"),
                            ("huawei", "华为云"),
                            ("vcenter", "vCenter"),
                            ("meicheng", "美橙"),
                            ("other", "其他"),
                        ],
                        db_comment="云平台类型枚举值",
                        default="tencent",
                        help_text="云平台类型枚举：腾讯云/阿里云/AWS/Azure/华为云/vCenter/美橙/其他",
                        max_length=32,
                        verbose_name="平台类型",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True,
                        db_comment="API访问地址",
                        help_text="API 访问地址，如 https://cvm.tencentcloudapi.com",
                        max_length=512,
                        null=True,
                        verbose_name="API 端点",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        db_comment="默认区域标识",
                        help_text="默认区域标识，如 ap-guangzhou",
                        max_length=128,
                        null=True,
                        verbose_name="默认区域",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="平台启用状态：True启用/False禁用",
                        default=True,
                        help_text="平台是否启用，禁用后不可用于新建凭据",
                        verbose_name="启用状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "云平台实例",
                "verbose_name_plural": "云平台实例",
                "db_table_comment": "云平台实例表，记录不同云服务商或基础设施的连接信息",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("access_key", "Access Key 密钥对"),
                            ("password", "用户名/密码"),
                            ("api_token", "API Token"),
                        ],
                        db_comment="凭据类型枚举值",
                        help_text="凭据类型枚举：access_key/password/api_token",
                        max_length=32,
                        verbose_name="凭据类型",
                    ),
                ),
                (
                    "credential_name",
                    models.CharField(
                        db_comment="自定义凭据标识名称",
                        help_text="自定义凭据标识，如：运维账号",
                        max_length=128,
                        verbose_name="凭据名称",
                    ),
                ),
                (
                    "access_key",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        db_comment="Access Key ID（加密存储）",
                        default="",
                        help_text="云平台 Access Key ID（加密存储）",
                        null=True,
                        verbose_name="Access Key ID",
                    ),
                ),
                (
                    "access_secret",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        db_comment="Secret Access Key（加密存储）",
                        default="",
                        help_text="云平台 Secret Access Key（加密存储）",
                        null=True,
                        verbose_name="Secret Access Key",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        db_comment="登录用户名",
                        help_text="登录用户名",
                        max_length=128,
                        null=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        db_comment="登录密码（加密存储）",
                        default="",
                        help_text="登录密码（加密存储）",
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        db_comment="关联邮箱地址",
                        help_text="关联邮箱（美橙等部分服务商认证需要）",
                        max_length=254,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "api_token",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        db_comment="API访问令牌（加密存储）",
                        default="",
                        help_text="API 访问令牌（加密存储）",
                        null=True,
                        verbose_name="API Token",
                    ),
                ),
                (
                    "token_expire_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Token过期时间，为空表示永不过期",
                        help_text="Token 过期时间，为空表示永不过期",
                        null=True,
                        verbose_name="Token 过期时间",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        db_comment="扩展JSON键值对，适配个性化认证需求",
                        default=dict,
                        help_text="扩展 JSON 字段，存储不同平台的个性化认证键值对",
                        null=True,
                        verbose_name="扩展数据",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        db_comment="凭据用途说明",
                        help_text="凭据用途说明",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="凭据启用状态：True启用/False禁用",
                        default=True,
                        help_text="凭据是否启用，禁用后不可用于API调用",
                        verbose_name="启用状态",
                    ),
                ),
            ],
            options={
                "verbose_name": "云平台凭据",
                "verbose_name_plural": "云平台凭据",
                "db_table_comment": "云平台凭据表，存储不同认证方式的加密凭据信息",
                "ordering": ["platform", "-created_time"],
            },
        ),
    ]
