# Generated by Django 5.2.9 on 2026-07-14 08:04

import apps.common.fields.encrypted
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_init"),
        ("system", "0003_userloginlog_channel_name_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CloudPlatform",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="自定义平台实例名称，如：生产环境-腾讯云",
                        max_length=128,
                        unique=True,
                        verbose_name="平台名称",
                    ),
                ),
                (
                    "platform_type",
                    models.CharField(
                        choices=[
                            ("tencent", "腾讯云"),
                            ("aliyun", "阿里云"),
                            ("aws", "AWS"),
                            ("azure", "Azure"),
                            ("huawei", "华为云"),
                            ("vcenter", "vCenter"),
                            ("meicheng", "美橙"),
                            ("other", "其他"),
                        ],
                        default="tencent",
                        max_length=32,
                        verbose_name="平台类型",
                    ),
                ),
                (
                    "endpoint",
                    models.CharField(
                        blank=True,
                        help_text="API 访问地址，如 https://cvm.tencentcloudapi.com",
                        max_length=512,
                        null=True,
                        verbose_name="API 端点",
                    ),
                ),
                (
                    "region",
                    models.CharField(
                        blank=True,
                        help_text="默认区域标识，如 ap-guangzhou",
                        max_length=128,
                        null=True,
                        verbose_name="默认区域",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        help_text="平台归属的公司主体（个人注册或无公司归属可不填）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="platforms",
                        to="company.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "云平台实例",
                "verbose_name_plural": "云平台实例",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="Credential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created time"
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="Updated time"
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "credential_type",
                    models.CharField(
                        choices=[
                            ("access_key", "Access Key 密钥对"),
                            ("password", "用户名/密码"),
                            ("api_token", "API Token"),
                        ],
                        max_length=32,
                        verbose_name="凭据类型",
                    ),
                ),
                (
                    "credential_name",
                    models.CharField(
                        help_text="自定义凭据标识，如：运维账号",
                        max_length=128,
                        verbose_name="凭据名称",
                    ),
                ),
                (
                    "access_key",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="云平台 Access Key ID（加密存储）",
                        null=True,
                        verbose_name="Access Key ID",
                    ),
                ),
                (
                    "access_secret",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="云平台 Secret Access Key（加密存储）",
                        null=True,
                        verbose_name="Secret Access Key",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        blank=True,
                        help_text="登录用户名",
                        max_length=128,
                        null=True,
                        verbose_name="用户名",
                    ),
                ),
                (
                    "password",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="登录密码（加密存储）",
                        null=True,
                        verbose_name="密码",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="关联邮箱（美橙等部分服务商认证需要）",
                        max_length=254,
                        null=True,
                        verbose_name="邮箱",
                    ),
                ),
                (
                    "api_token",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        default="",
                        help_text="API 访问令牌（加密存储）",
                        null=True,
                        verbose_name="API Token",
                    ),
                ),
                (
                    "token_expire_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Token 过期时间，为空表示永不过期",
                        null=True,
                        verbose_name="Token 过期时间",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="扩展 JSON 字段，存储不同平台的个性化认证键值对",
                        null=True,
                        verbose_name="扩展数据",
                    ),
                ),
                (
                    "remark",
                    models.TextField(
                        blank=True,
                        help_text="凭据用途说明",
                        null=True,
                        verbose_name="备注",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, verbose_name="启用状态"),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        help_text="该凭据归属的云平台实例",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credentials",
                        to="cloud_platform.cloudplatform",
                        verbose_name="所属平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "云平台凭据",
                "verbose_name_plural": "云平台凭据",
                "ordering": ["platform", "-created_time"],
            },
        ),
    ]
