# Generated by Django 5.2.9 on 2026-07-14 10:20

import apps.common.fields.encrypted
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_platform", "0001_init"),
        (
            "company",
            "0002_alter_company_table_comment_alter_company_is_active_and_more",
        ),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="cloudplatform",
            table_comment="云平台实例表，记录不同云服务商或基础设施的连接信息",
        ),
        migrations.AlterModelTableComment(
            name="credential",
            table_comment="云平台凭据表，存储不同认证方式的加密凭据信息",
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_comment="平台归属的公司主体ID，关联company表",
                help_text="平台归属的公司主体（个人注册或无公司归属可不填）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platforms",
                to="company.company",
                verbose_name="所属公司",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="endpoint",
            field=models.CharField(
                blank=True,
                db_comment="API访问地址",
                help_text="API 访问地址，如 https://cvm.tencentcloudapi.com",
                max_length=512,
                null=True,
                verbose_name="API 端点",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="is_active",
            field=models.BooleanField(
                db_comment="平台启用状态：True启用/False禁用",
                default=True,
                help_text="平台是否启用，禁用后不可用于新建凭据",
                verbose_name="启用状态",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="name",
            field=models.CharField(
                db_comment="平台实例名称，唯一",
                help_text="自定义平台实例名称，如：生产环境-腾讯云",
                max_length=128,
                unique=True,
                verbose_name="平台名称",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="platform_type",
            field=models.CharField(
                choices=[
                    ("tencent", "腾讯云"),
                    ("aliyun", "阿里云"),
                    ("aws", "AWS"),
                    ("azure", "Azure"),
                    ("huawei", "华为云"),
                    ("vcenter", "vCenter"),
                    ("meicheng", "美橙"),
                    ("other", "其他"),
                ],
                db_comment="云平台类型枚举值",
                default="tencent",
                help_text="云平台类型枚举：腾讯云/阿里云/AWS/Azure/华为云/vCenter/美橙/其他",
                max_length=32,
                verbose_name="平台类型",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="region",
            field=models.CharField(
                blank=True,
                db_comment="默认区域标识",
                help_text="默认区域标识，如 ap-guangzhou",
                max_length=128,
                null=True,
                verbose_name="默认区域",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="access_key",
            field=apps.common.fields.encrypted.EncryptedTextField(
                blank=True,
                db_comment="Access Key ID（加密存储）",
                default="",
                help_text="云平台 Access Key ID（加密存储）",
                null=True,
                verbose_name="Access Key ID",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="access_secret",
            field=apps.common.fields.encrypted.EncryptedTextField(
                blank=True,
                db_comment="Secret Access Key（加密存储）",
                default="",
                help_text="云平台 Secret Access Key（加密存储）",
                null=True,
                verbose_name="Secret Access Key",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="api_token",
            field=apps.common.fields.encrypted.EncryptedTextField(
                blank=True,
                db_comment="API访问令牌（加密存储）",
                default="",
                help_text="API 访问令牌（加密存储）",
                null=True,
                verbose_name="API Token",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="credential_name",
            field=models.CharField(
                db_comment="自定义凭据标识名称",
                help_text="自定义凭据标识，如：运维账号",
                max_length=128,
                verbose_name="凭据名称",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="credential_type",
            field=models.CharField(
                choices=[
                    ("access_key", "Access Key 密钥对"),
                    ("password", "用户名/密码"),
                    ("api_token", "API Token"),
                ],
                db_comment="凭据类型枚举值",
                help_text="凭据类型枚举：access_key/password/api_token",
                max_length=32,
                verbose_name="凭据类型",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="email",
            field=models.EmailField(
                blank=True,
                db_comment="关联邮箱地址",
                help_text="关联邮箱（美橙等部分服务商认证需要）",
                max_length=254,
                null=True,
                verbose_name="邮箱",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="extra_data",
            field=models.JSONField(
                blank=True,
                db_comment="扩展JSON键值对，适配个性化认证需求",
                default=dict,
                help_text="扩展 JSON 字段，存储不同平台的个性化认证键值对",
                null=True,
                verbose_name="扩展数据",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="is_active",
            field=models.BooleanField(
                db_comment="凭据启用状态：True启用/False禁用",
                default=True,
                help_text="凭据是否启用，禁用后不可用于API调用",
                verbose_name="启用状态",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="password",
            field=apps.common.fields.encrypted.EncryptedTextField(
                blank=True,
                db_comment="登录密码（加密存储）",
                default="",
                help_text="登录密码（加密存储）",
                null=True,
                verbose_name="密码",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="platform",
            field=models.ForeignKey(
                db_comment="凭据归属的云平台实例ID，关联cloudplatform表",
                help_text="该凭据归属的云平台实例",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="cloud_platform.cloudplatform",
                verbose_name="所属平台",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="remark",
            field=models.TextField(
                blank=True,
                db_comment="凭据用途说明",
                help_text="凭据用途说明",
                null=True,
                verbose_name="备注",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="token_expire_time",
            field=models.DateTimeField(
                blank=True,
                db_comment="Token过期时间，为空表示永不过期",
                help_text="Token 过期时间，为空表示永不过期",
                null=True,
                verbose_name="Token 过期时间",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="username",
            field=models.CharField(
                blank=True,
                db_comment="登录用户名",
                help_text="登录用户名",
                max_length=128,
                null=True,
                verbose_name="用户名",
            ),
        ),
    ]
