# Generated by Django 5.2.9 on 2026-07-15 03:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cloud_platform", "0001_initial"),
        ("company", "0001_initial"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudplatform",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_comment="平台归属的公司主体ID，关联company表",
                help_text="平台归属的公司主体（个人注册或无公司归属可不填）",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="platforms",
                to="company.company",
                verbose_name="所属公司",
            ),
        ),
        migrations.AddField(
            model_name="cloudplatform",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                help_text="User who created this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="cloudplatform",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                help_text="Department to which this record belongs, used for data-level permission filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="cloudplatform",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                help_text="User who created this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                help_text="Department to which this record belongs, used for data-level permission filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AddField(
            model_name="credential",
            name="platform",
            field=models.ForeignKey(
                db_comment="凭据归属的云平台实例ID，关联cloudplatform表",
                help_text="该凭据归属的云平台实例",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="credentials",
                to="cloud_platform.cloudplatform",
                verbose_name="所属平台",
            ),
        ),
    ]
