# Generated by Django 5.2.9 on 2026-07-15 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_platform", "0002_alter_cloudplatform_table_comment_and_more"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudplatform",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                help_text="Timestamp automatically set when the record is first created",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                help_text="User who created this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                help_text="Department to which this record belongs, used for data-level permission filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                help_text="Optional brief description or remark for this record",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="cloudplatform",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                help_text="Timestamp automatically updated each time the record is saved",
                null=True,
                verbose_name="Updated time",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True,
                db_comment="创建时间",
                help_text="Timestamp automatically set when the record is first created",
                null=True,
                verbose_name="Created time",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                db_comment="创建人",
                help_text="User who created this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="creator_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creator",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="dept_belong",
            field=models.ForeignKey(
                blank=True,
                db_comment="数据归属部门",
                help_text="Department to which this record belongs, used for data-level permission filtering",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="dept_belong_query",
                to="system.deptinfo",
                verbose_name="Data ownership department",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="description",
            field=models.CharField(
                blank=True,
                db_comment="描述信息",
                help_text="Optional brief description or remark for this record",
                max_length=256,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="modifier",
            field=models.ForeignKey(
                blank=True,
                db_comment="修改人",
                help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                related_query_name="modifier_query",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modifier",
            ),
        ),
        migrations.AlterField(
            model_name="credential",
            name="updated_time",
            field=models.DateTimeField(
                auto_now=True,
                db_comment="更新时间",
                help_text="Timestamp automatically updated each time the record is saved",
                null=True,
                verbose_name="Updated time",
            ),
        ),
    ]
