# Generated by Django 5.2.9 on 2026-07-15 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_platform", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cloudplatform",
            name="account_balance",
            field=models.DecimalField(
                blank=True,
                db_comment="云平台账户实时余额（元），不支持余额查询的平台为0",
                decimal_places=2,
                default=0,
                help_text="云平台账户实时余额，仅支持余额查询的平台有效，单位为元",
                max_digits=14,
                verbose_name="账户余额（元）",
            ),
        ),
        migrations.AddField(
            model_name="cloudplatform",
            name="balance_updated_time",
            field=models.DateTimeField(
                blank=True,
                db_comment="最近一次余额查询时间",
                help_text="最近一次余额查询的时间，为空表示从未查询",
                null=True,
                verbose_name="余额更新时间",
            ),
        ),
    ]
