# Generated by Django 5.2.9 on 2026-07-15 08:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_platform", "0003_add_account_balance"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountBalance",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "balance",
                    models.DecimalField(
                        db_comment="当日账户余额（元）",
                        decimal_places=2,
                        help_text="当日账户余额",
                        max_digits=14,
                        verbose_name="余额（元）",
                    ),
                ),
                (
                    "record_date",
                    models.DateField(
                        db_comment="余额快照日期",
                        help_text="余额快照对应的日期",
                        verbose_name="记录日期",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        db_comment="云平台实例ID，关联cloudplatform表",
                        help_text="所属云平台实例",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="balance_records",
                        to="cloud_platform.cloudplatform",
                        verbose_name="云平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "账户余额记录",
                "verbose_name_plural": "账户余额记录",
                "db_table_comment": "云平台账户余额每日快照表，按天存储最近30天数据",
                "ordering": ["platform", "-record_date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("platform", "record_date"),
                        name="unique_platform_balance_date",
                    )
                ],
            },
        ),
    ]
