# Generated by Django 5.2.9 on 2026-07-15 09:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_platform", "0004_add_balance_history"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("manual", "手动触发"),
                            ("scheduled", "定时触发"),
                            ("webhook", "Webhook 触发"),
                        ],
                        db_comment="同步触发类型",
                        help_text="同步任务的触发方式：手动触发/定时触发/Webhook 触发",
                        max_length=32,
                        verbose_name="触发类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "已完成"),
                            ("partial", "部分成功"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        db_comment="同步任务状态",
                        default="pending",
                        help_text="同步任务当前状态：等待中/运行中/已完成/部分成功/失败/已取消",
                        max_length=32,
                        verbose_name="同步状态",
                    ),
                ),
                (
                    "resources",
                    models.JSONField(
                        db_comment="同步资源类型列表（JSON数组）",
                        default=list,
                        help_text='本次同步包含的资源类型列表，如：["server", "domain"]',
                        verbose_name="同步资源",
                    ),
                ),
                (
                    "total_created",
                    models.IntegerField(
                        db_comment="新建资源数量",
                        default=0,
                        help_text="本次同步新建的资源数量",
                        verbose_name="新建数量",
                    ),
                ),
                (
                    "total_updated",
                    models.IntegerField(
                        db_comment="更新资源数量",
                        default=0,
                        help_text="本次同步更新的资源数量",
                        verbose_name="更新数量",
                    ),
                ),
                (
                    "total_terminated",
                    models.IntegerField(
                        db_comment="终止资源数量",
                        default=0,
                        help_text="本次同步发现已终止/删除的资源数量",
                        verbose_name="终止数量",
                    ),
                ),
                (
                    "total_errors",
                    models.IntegerField(
                        db_comment="累计错误数量",
                        default=0,
                        help_text="本次同步累计错误数量",
                        verbose_name="错误数量",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="同步开始时间",
                        help_text="同步任务开始执行的时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="同步结束时间",
                        help_text="同步任务执行结束的时间",
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "error_detail",
                    models.JSONField(
                        db_comment="错误详情列表（JSON数组）",
                        default=list,
                        help_text="同步过程中的错误详情列表，每项含 item 和 error 字段",
                        verbose_name="错误详情",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        db_comment="所属云平台实例ID，关联cloud_platform表",
                        help_text="所属云平台实例",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sync_records",
                        to="cloud_platform.cloudplatform",
                        verbose_name="云平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步记录",
                "verbose_name_plural": "同步记录",
                "db_table_comment": "同步记录表，记录每次同步任务的整体执行情况",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="SyncAgentLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "agent_name",
                    models.CharField(
                        db_comment="Agent/子模块名称",
                        help_text="执行同步的 Agent 或子模块名称，如 tencent-server",
                        max_length=128,
                        verbose_name="Agent 名称",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("server", "云服务器"),
                            ("domain", "域名"),
                            ("dns_record", "DNS 解析记录"),
                            ("balance", "账户余额"),
                        ],
                        db_comment="同步资源类型",
                        help_text="Agent 负责同步的资源类型",
                        max_length=32,
                        verbose_name="资源类型",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("running", "运行中"),
                            ("success", "已完成"),
                            ("failed", "失败"),
                        ],
                        db_comment="Agent执行状态",
                        default="pending",
                        help_text="Agent 子任务的执行状态",
                        max_length=32,
                        verbose_name="执行状态",
                    ),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Agent开始执行时间",
                        help_text="Agent 子任务开始执行的时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "finished_at",
                    models.DateTimeField(
                        blank=True,
                        db_comment="Agent结束执行时间",
                        help_text="Agent 子任务执行结束的时间",
                        null=True,
                        verbose_name="结束时间",
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True,
                        db_comment="Agent详细执行日志",
                        default="",
                        help_text="Agent 执行的详细日志输出",
                        verbose_name="执行日志",
                    ),
                ),
                (
                    "created_count",
                    models.IntegerField(
                        db_comment="Agent新建资源数量",
                        default=0,
                        help_text="Agent 新建的资源数量",
                        verbose_name="新建数量",
                    ),
                ),
                (
                    "updated_count",
                    models.IntegerField(
                        db_comment="Agent更新资源数量",
                        default=0,
                        help_text="Agent 更新的资源数量",
                        verbose_name="更新数量",
                    ),
                ),
                (
                    "terminated_count",
                    models.IntegerField(
                        db_comment="Agent终止资源数量",
                        default=0,
                        help_text="Agent 发现已终止/删除的资源数量",
                        verbose_name="终止数量",
                    ),
                ),
                (
                    "error_count",
                    models.IntegerField(
                        db_comment="Agent错误数量",
                        default=0,
                        help_text="Agent 子任务的错误数量",
                        verbose_name="错误数量",
                    ),
                ),
                (
                    "error_detail",
                    models.JSONField(
                        db_comment="Agent错误详情列表（JSON数组）",
                        default=list,
                        help_text="Agent 子任务的错误详情列表",
                        verbose_name="错误详情",
                    ),
                ),
                (
                    "retry_count",
                    models.IntegerField(
                        db_comment="Agent重试次数",
                        default=0,
                        help_text="Agent 子任务的重试次数",
                        verbose_name="重试次数",
                    ),
                ),
                (
                    "extra_data",
                    models.JSONField(
                        db_comment="Agent扩展数据（JSON对象）",
                        default=dict,
                        help_text="Agent 特定的扩展数据，如进度信息、中间状态等",
                        verbose_name="扩展数据",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "sync_record",
                    models.ForeignKey(
                        db_comment="所属同步记录ID，关联sync_record表",
                        help_text="所属的同步记录",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agent_logs",
                        to="cloud_platform.syncrecord",
                        verbose_name="同步记录",
                    ),
                ),
            ],
            options={
                "verbose_name": "同步Agent日志",
                "verbose_name_plural": "同步Agent日志",
                "db_table_comment": "同步Agent执行日志表，记录每个子任务的执行详情",
                "ordering": ["created_time"],
                "unique_together": {("sync_record", "agent_name")},
            },
        ),
    ]
