# Generated by Django 5.2.9 on 2026-07-20 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cloud_platform", "0005_syncrecord_syncagentlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cloudplatform",
            name="platform_type",
            field=models.CharField(
                choices=[
                    ("tencent", "腾讯云"),
                    ("aliyun", "阿里云"),
                    ("aws", "AWS"),
                    ("azure", "Azure"),
                    ("huawei", "华为云"),
                    ("volcengine", "火山引擎"),
                    ("vcenter", "vCenter"),
                    ("meicheng", "美橙"),
                    ("other", "其他"),
                ],
                db_comment="云平台类型枚举值",
                default="tencent",
                help_text="云平台类型枚举：腾讯云/阿里云/AWS/Azure/华为云/vCenter/美橙/其他",
                max_length=32,
                verbose_name="平台类型",
            ),
        ),
    ]
