# Generated by Django 5.2.9 on 2026-07-20 02:52

import apps.common.core.models
import apps.common.fields.encrypted
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("asset", "0010_dnsrecord_is_ssl_enabled_and_more"),
        ("cloud_platform", "0006_alter_cloudplatform_platform_type"),
        ("company", "0003_change_file_fields"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # 使用 SeparateDatabaseAndState：仅在迁移状态中创建模型，
    # 数据库层面不执行任何操作（表已由 asset app 创建，db_table 保持原表名不变）。
    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.CreateModel(
                    name="Domain",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "domain_name",
                    models.CharField(
                        db_comment="完整域名，唯一",
                        help_text="完整域名，如 example.com，唯一",
                        max_length=256,
                        unique=True,
                        verbose_name="域名",
                    ),
                ),
                (
                    "registrar",
                    models.CharField(
                        blank=True,
                        db_comment="域名注册商名称",
                        help_text="域名注册服务商，如 腾讯云/阿里云/GoDaddy",
                        max_length=128,
                        null=True,
                        verbose_name="注册商",
                    ),
                ),
                (
                    "registration_time",
                    models.DateField(
                        blank=True,
                        db_comment="域名注册日期",
                        help_text="域名首次注册日期",
                        null=True,
                        verbose_name="注册时间",
                    ),
                ),
                (
                    "expire_time",
                    models.DateField(
                        blank=True,
                        db_comment="域名到期日期",
                        help_text="域名到期日期",
                        null=True,
                        verbose_name="到期时间",
                    ),
                ),
                (
                    "dns_server",
                    models.TextField(
                        blank=True,
                        db_comment="DNS解析服务器列表",
                        help_text="DNS 服务器列表，多个用逗号或换行分隔",
                        null=True,
                        verbose_name="DNS 服务器",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "正常"),
                            ("expired", "已过期"),
                            ("pending", "注册中"),
                            ("transferring", "转移中"),
                            ("locked", "已锁定"),
                            ("forbidden", "已封禁"),
                            ("unverified", "未实名"),
                            ("other", "其他"),
                        ],
                        db_comment="域名状态枚举值",
                        default="active",
                        help_text="域名当前状态",
                        max_length=32,
                        verbose_name="域名状态",
                    ),
                ),
                (
                    "owner_name",
                    models.CharField(
                        blank=True,
                        db_comment="域名所有者姓名",
                        help_text="域名所有者/联系人姓名",
                        max_length=128,
                        null=True,
                        verbose_name="所有者",
                    ),
                ),
                (
                    "is_ssl_enabled",
                    models.BooleanField(
                        db_comment="是否启用SSL证书",
                        default=False,
                        help_text="是否已部署 SSL 证书",
                        verbose_name="SSL 证书",
                    ),
                ),
                (
                    "ssl_expire_time",
                    models.DateField(
                        blank=True,
                        db_comment="SSL证书到期日期",
                        help_text="SSL 证书到期日期",
                        null=True,
                        verbose_name="SSL 到期时间",
                    ),
                ),
                (
                    "domain_certificate",
                    models.FileField(
                        blank=True,
                        db_comment="域名证书文件路径",
                        help_text="域名注册证书/实名认证证书扫描件",
                        null=True,
                        upload_to=apps.common.core.models.upload_directory_path,
                        verbose_name="域名证书",
                    ),
                ),
                (
                    "security_contact",
                    models.CharField(
                        blank=True,
                        db_comment="安全责任人姓名",
                        help_text="域名安全责任人姓名",
                        max_length=64,
                        null=True,
                        verbose_name="安全责任人",
                    ),
                ),
                (
                    "security_contact_phone",
                    models.CharField(
                        blank=True,
                        db_comment="安全责任人电话",
                        help_text="安全责任人联系电话",
                        max_length=32,
                        null=True,
                        verbose_name="安全责任人电话",
                    ),
                ),
                (
                    "service_contact",
                    models.CharField(
                        blank=True,
                        db_comment="服务负责人姓名",
                        help_text="域名服务/运维负责人姓名",
                        max_length=64,
                        null=True,
                        verbose_name="服务负责人",
                    ),
                ),
                (
                    "service_contact_phone",
                    models.CharField(
                        blank=True,
                        db_comment="服务负责人电话",
                        help_text="服务负责人联系电话",
                        max_length=32,
                        null=True,
                        verbose_name="服务负责人电话",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="启用状态：True启用/False禁用",
                        default=True,
                        help_text="是否纳入资产管理范围",
                        verbose_name="启用状态",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_comment="归属公司主体ID，关联company表",
                        help_text="域名归属的公司主体",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains",
                        to="company.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "platform",
                    models.ForeignKey(
                        blank=True,
                        db_comment="归属云平台实例ID，关联cloudplatform表",
                        help_text="域名解析所在的云平台（可选）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="domains",
                        to="cloud_platform.cloudplatform",
                        verbose_name="归属云平台",
                    ),
                ),
            ],
            options={
                "verbose_name": "域名",
                "verbose_name_plural": "域名",
                "db_table": "asset_domain",
                "db_table_comment": "域名资产表，记录注册域名及SSL证书信息",
                "ordering": ["-expire_time"],
            },
        ),
        migrations.CreateModel(
            name="DnsRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("TXT", "TXT"),
                            ("NS", "NS"),
                            ("SRV", "SRV"),
                            ("CAA", "CAA"),
                            ("other", "其他"),
                        ],
                        db_comment="DNS记录类型枚举值",
                        help_text="DNS 记录类型：A/AAAA/CNAME/MX/TXT/NS/SRV/CAA",
                        max_length=16,
                        verbose_name="记录类型",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        db_comment="主机记录前缀",
                        help_text="主机记录前缀，如 @、www、mail",
                        max_length=256,
                        verbose_name="主机记录",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        db_comment="解析记录值",
                        help_text="解析目标，A记录为IP、CNAME为目标域名、MX为邮件服务器地址等",
                        verbose_name="记录值",
                    ),
                ),
                (
                    "ttl",
                    models.PositiveIntegerField(
                        db_comment="TTL生存时间（秒）",
                        default=600,
                        help_text="生存时间，默认 600 秒",
                        verbose_name="TTL（秒）",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_comment="MX/SRV记录优先级",
                        help_text="MX/SRV 记录的优先级，值越小优先级越高",
                        null=True,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="启用状态：True启用/False禁用",
                        default=True,
                        help_text="解析记录是否生效",
                        verbose_name="启用状态",
                    ),
                ),
                (
                    "is_ssl_enabled",
                    models.BooleanField(
                        db_comment="是否支持HTTPS",
                        default=False,
                        help_text="该子域名是否支持 HTTPS（由 SSL 定时检测自动更新）",
                        verbose_name="SSL 证书",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        db_comment="归属域名ID，关联domain表",
                        help_text="该解析记录归属的域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_records",
                        to="domain.domain",
                        verbose_name="所属域名",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS 解析记录",
                "verbose_name_plural": "DNS 解析记录",
                "db_table": "asset_dnsrecord",
                "db_table_comment": "域名DNS解析记录表，存储每个域名的解析配置",
                "ordering": ["domain", "record_type", "host"],
            },
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icp_number",
                    models.CharField(
                        blank=True,
                        db_comment="ICP备案号",
                        help_text="ICP 备案号，如 京ICP备2023000001号",
                        max_length=64,
                        null=True,
                        verbose_name="ICP 备案号",
                    ),
                ),
                (
                    "icp_filing_date",
                    models.DateField(
                        blank=True,
                        db_comment="ICP备案日期",
                        help_text="ICP 备案通过日期",
                        null=True,
                        verbose_name="ICP 备案日期",
                    ),
                ),
                (
                    "icp_unit_name",
                    models.CharField(
                        blank=True,
                        db_comment="ICP备案主体名称",
                        help_text="ICP 备案主体名称（单位/个人名称）",
                        max_length=256,
                        null=True,
                        verbose_name="ICP 备案主体",
                    ),
                ),
                (
                    "icp_status",
                    models.CharField(
                        choices=[
                            ("not_filed", "未备案"),
                            ("filed", "已备案"),
                            ("pending_confirm", "待人工确认"),
                            ("changing", "变更中"),
                        ],
                        db_comment="ICP备案状态枚举值",
                        default="not_filed",
                        help_text="ICP 备案当前状态：未备案/已备案/待人工确认/变更中",
                        max_length=32,
                        verbose_name="ICP 备案状态",
                    ),
                ),
                (
                    "icp_check_status",
                    models.CharField(
                        choices=[
                            ("not_checked", "未检测"),
                            ("passed", "检测通过"),
                            ("suspected_missing", "疑似未悬挂"),
                            ("no_www_record", "无www解析"),
                            ("check_failed", "检测失败"),
                        ],
                        db_comment="ICP预检测状态枚举值",
                        default="not_checked",
                        help_text="首页悬挂备案号预检测结果",
                        max_length=32,
                        verbose_name="ICP 预检测状态",
                    ),
                ),
                (
                    "icp_has_www_record",
                    models.BooleanField(
                        db_comment="是否存在www解析记录",
                        default=False,
                        help_text="域名是否存在 www 子域名的 DNS 解析记录",
                        verbose_name="有www解析",
                    ),
                ),
                (
                    "icp_footer_content",
                    models.TextField(
                        blank=True,
                        db_comment="首页页脚文本内容",
                        help_text="首页页脚区域抓取到的文本内容（预检测时填充）",
                        null=True,
                        verbose_name="页脚内容",
                    ),
                ),
                (
                    "icp_check_conclusion",
                    models.TextField(
                        blank=True,
                        db_comment="预检测结论描述",
                        help_text="预检测的详细结论描述",
                        null=True,
                        verbose_name="检测结论",
                    ),
                ),
                (
                    "icp_check_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="最近预检测时间",
                        help_text="最近一次预检测执行时间",
                        null=True,
                        verbose_name="检测时间",
                    ),
                ),
                (
                    "ps_filing_number",
                    models.CharField(
                        blank=True,
                        db_comment="公安备案号",
                        help_text="公安联网备案号，如 京公网安备110100000001号",
                        max_length=64,
                        null=True,
                        verbose_name="公安备案号",
                    ),
                ),
                (
                    "ps_filing_date",
                    models.DateField(
                        blank=True,
                        db_comment="公安备案日期",
                        help_text="公安联网备案通过日期",
                        null=True,
                        verbose_name="公安备案日期",
                    ),
                ),
                (
                    "ps_unit_name",
                    models.CharField(
                        blank=True,
                        db_comment="公安备案主体名称",
                        help_text="公安备案主体名称",
                        max_length=256,
                        null=True,
                        verbose_name="公安备案主体",
                    ),
                ),
                (
                    "ps_public_security_agency",
                    models.CharField(
                        blank=True,
                        db_comment="备案公安机关名称",
                        help_text="受理备案的公安机关名称",
                        max_length=128,
                        null=True,
                        verbose_name="备案公安机关",
                    ),
                ),
                (
                    "ps_status",
                    models.CharField(
                        choices=[
                            ("not_filed", "未备案"),
                            ("filed", "已备案"),
                            ("pending_confirm", "待人工确认"),
                            ("changing", "变更中"),
                        ],
                        db_comment="公安备案状态枚举值",
                        default="not_filed",
                        help_text="公安备案当前状态：未备案/已备案/待人工确认",
                        max_length=32,
                        verbose_name="公安备案状态",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_comment="归属公司主体ID",
                        help_text="备案主体归属的公司（冗余字段，用于筛选）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filings",
                        to="company.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "domain",
                    models.OneToOneField(
                        db_comment="关联域名ID，一对一",
                        help_text="该备案记录关联的域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing",
                        to="domain.domain",
                        verbose_name="关联域名",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "备案信息",
                "verbose_name_plural": "备案信息",
                "db_table": "asset_filing",
                "db_table_comment": "备案信息统一表，同时存储ICP备案与公安备案，通过 icp_*/ps_* 前缀字段区分",
                "ordering": ["-created_time"],
            },
        ),
        migrations.CreateModel(
            name="SslCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        db_comment="SHA256指纹，唯一标识",
                        help_text="SHA256 指纹，用于判断证书是否完全一致（去重依据）",
                        max_length=128,
                        unique=True,
                        verbose_name="证书指纹",
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True,
                        db_comment="主体CN",
                        help_text="证书主体 Common Name，通常为域名",
                        max_length=256,
                        null=True,
                        verbose_name="主体通用名",
                    ),
                ),
                (
                    "subject_o",
                    models.CharField(
                        blank=True,
                        db_comment="主体O",
                        help_text="证书主体 Organization",
                        max_length=256,
                        null=True,
                        verbose_name="主体组织",
                    ),
                ),
                (
                    "subject_ou",
                    models.CharField(
                        blank=True,
                        db_comment="主体OU",
                        help_text="证书主体 Organizational Unit",
                        max_length=256,
                        null=True,
                        verbose_name="主体组织单元",
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True,
                        db_comment="颁发机构CN",
                        help_text="颁发机构 Common Name",
                        max_length=256,
                        null=True,
                        verbose_name="颁发机构通用名",
                    ),
                ),
                (
                    "issuer_o",
                    models.CharField(
                        blank=True,
                        db_comment="颁发机构O",
                        help_text="颁发机构 Organization",
                        max_length=256,
                        null=True,
                        verbose_name="颁发机构组织",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_comment="证书序列号",
                        help_text="证书唯一序列号（十六进制）",
                        max_length=128,
                        null=True,
                        verbose_name="序列号",
                    ),
                ),
                (
                    "signature_algorithm",
                    models.CharField(
                        blank=True,
                        db_comment="签名算法",
                        help_text="证书签名哈希算法，如 sha256",
                        max_length=64,
                        null=True,
                        verbose_name="签名算法",
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True,
                        db_comment="证书有效期起始",
                        help_text="证书生效时间（UTC）",
                        null=True,
                        verbose_name="有效期起始",
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True,
                        db_comment="证书有效期结束",
                        help_text="证书到期时间（UTC）",
                        null=True,
                        verbose_name="有效期结束",
                    ),
                ),
                (
                    "san_domains",
                    models.JSONField(
                        blank=True,
                        db_comment="SAN域名列表",
                        default=list,
                        help_text="Subject Alternative Names 列表（证书覆盖的所有域名）",
                        verbose_name="备用域名",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_comment="证书是否有效",
                        default=False,
                        help_text="检测时证书是否在有效期内",
                        verbose_name="是否有效",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="最近检测时间",
                        help_text="最近一次 SSL 证书检测时间",
                        null=True,
                        verbose_name="检测时间",
                    ),
                ),
                (
                    "certificate_pem",
                    models.TextField(
                        blank=True,
                        db_comment="终端证书PEM",
                        help_text="终端证书 PEM 格式内容（自动检测填充）",
                        null=True,
                        verbose_name="终端证书",
                    ),
                ),
                (
                    "intermediate_pem",
                    models.TextField(
                        blank=True,
                        db_comment="中间证书链PEM",
                        help_text="中间证书链 PEM 格式内容（自动检测填充，可能包含多张中间证书）",
                        null=True,
                        verbose_name="中间证书",
                    ),
                ),
                (
                    "private_key_pem",
                    apps.common.fields.encrypted.EncryptedTextField(
                        blank=True,
                        db_comment="私钥PEM（加密）",
                        help_text="私钥 PEM 格式内容（加密存储，需手动上传，无法自动检测）",
                        null=True,
                        verbose_name="私钥",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSL 证书",
                "verbose_name_plural": "SSL 证书",
                "db_table": "asset_sslcertificate",
                "db_table_comment": "SSL证书详细信息表，相同证书（指纹去重）只存一条，被多个域名关联",
                "ordering": ["-created_time"],
            },
        ),
        migrations.AddField(
            model_name="domain",
            name="ssl_certificate",
            field=models.ForeignKey(
                blank=True,
                db_comment="关联SSL证书记录ID",
                help_text="关联的 SSL 证书记录，相同证书共用一条记录",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domains",
                to="domain.sslcertificate",
                verbose_name="SSL 证书",
            ),
        ),
            ],
        ),
    ]
