# Generated by Django 5.2.9 on 2026-07-15 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localserver",
            name="memory",
        ),
        migrations.AddField(
            model_name="localserver",
            name="cpu_detail",
            field=models.JSONField(
                blank=True,
                db_comment="CPU详细配置JSON列表",
                default=list,
                help_text='每颗 CPU 的详细配置列表，格式：[{"slot":1,"model":"Intel Xeon Gold 6248R","cores":24,"threads":48,"frequency":"3.0GHz"},...]',
                null=True,
                verbose_name="CPU 详细配置",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="cpu_total_cores",
            field=models.PositiveSmallIntegerField(
                db_comment="所有CPU物理核心总数",
                default=0,
                help_text="所有 CPU 物理核心总数",
                verbose_name="总核心数",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="cpu_total_threads",
            field=models.PositiveSmallIntegerField(
                db_comment="所有CPU逻辑线程总数",
                default=0,
                help_text="所有 CPU 逻辑线程总数（含超线程）",
                verbose_name="总线程数",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="disk_count",
            field=models.PositiveSmallIntegerField(
                db_comment="物理硬盘块数",
                default=0,
                help_text="物理硬盘块数",
                verbose_name="硬盘数量",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="disk_detail",
            field=models.JSONField(
                blank=True,
                db_comment="硬盘详细配置JSON列表",
                default=list,
                help_text='每块硬盘的详细配置列表，格式：[{"slot":"Slot0","capacity":960,"type":"SSD","interface":"SATA","model":"Intel S4510"},...]',
                null=True,
                verbose_name="硬盘详细配置",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_count",
            field=models.PositiveSmallIntegerField(
                db_comment="物理内存条根数",
                default=0,
                help_text="物理内存条根数",
                verbose_name="内存条数量",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_detail",
            field=models.JSONField(
                blank=True,
                db_comment="内存详细配置JSON列表",
                default=list,
                help_text='每条内存的详细配置列表，格式：[{"slot":"DIMM_A1","capacity":32,"type":"DDR4","frequency":3200},...]',
                null=True,
                verbose_name="内存详细配置",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_frequency",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="内存频率（MHz）",
                help_text="内存工作频率，如 3200",
                null=True,
                verbose_name="内存频率（MHz）",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_total",
            field=models.PositiveIntegerField(
                db_comment="内存总量（GB）",
                default=0,
                help_text="所有内存条合计容量，单位 GB",
                verbose_name="内存总量（GB）",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_type",
            field=models.CharField(
                blank=True,
                db_comment="内存类型",
                help_text="内存类型，如 DDR4/DDR5",
                max_length=32,
                null=True,
                verbose_name="内存类型",
            ),
        ),
        migrations.AlterField(
            model_name="localserver",
            name="disk_total",
            field=models.PositiveIntegerField(
                db_comment="磁盘总容量（GB）",
                default=0,
                help_text="所有硬盘合计容量，单位 GB",
                verbose_name="磁盘总量（GB）",
            ),
        ),
    ]
