# Generated by Django 5.2.9 on 2026-07-15 08:22

import apps.asset.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0001_initial"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="localserver",
            name="memory",
        ),
        migrations.AddField(
            model_name="localserver",
            name="cpu_detail",
            field=models.JSONField(
                blank=True,
                db_comment="CPU详细配置JSON列表",
                default=list,
                help_text="每颗 CPU 的详细配置列表，结构定义见 apps.asset.structs.CpuDetailItem",
                null=True,
                validators=[
                    apps.asset.models.PydanticListValidator(
                        "apps.asset.structs.CpuDetailItem"
                    )
                ],
                verbose_name="CPU 详细配置",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="cpu_total_cores",
            field=models.PositiveSmallIntegerField(
                db_comment="所有CPU物理核心总数",
                default=0,
                help_text="所有 CPU 物理核心总数",
                verbose_name="总核心数",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="cpu_total_threads",
            field=models.PositiveSmallIntegerField(
                db_comment="所有CPU逻辑线程总数",
                default=0,
                help_text="所有 CPU 逻辑线程总数（含超线程）",
                verbose_name="总线程数",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="disk_count",
            field=models.PositiveSmallIntegerField(
                db_comment="物理硬盘块数",
                default=0,
                help_text="物理硬盘块数",
                verbose_name="硬盘数量",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="disk_detail",
            field=models.JSONField(
                blank=True,
                db_comment="硬盘详细配置JSON列表",
                default=list,
                help_text="每块硬盘的详细配置列表，结构定义见 apps.asset.structs.DiskDetailItem",
                null=True,
                validators=[
                    apps.asset.models.PydanticListValidator(
                        "apps.asset.structs.DiskDetailItem"
                    )
                ],
                verbose_name="硬盘详细配置",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_count",
            field=models.PositiveSmallIntegerField(
                db_comment="物理内存条根数",
                default=0,
                help_text="物理内存条根数",
                verbose_name="内存条数量",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_detail",
            field=models.JSONField(
                blank=True,
                db_comment="内存详细配置JSON列表",
                default=list,
                help_text="每条内存的详细配置列表，结构定义见 apps.asset.structs.MemoryDetailItem",
                null=True,
                validators=[
                    apps.asset.models.PydanticListValidator(
                        "apps.asset.structs.MemoryDetailItem"
                    )
                ],
                verbose_name="内存详细配置",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_frequency",
            field=models.PositiveIntegerField(
                blank=True,
                db_comment="内存频率（MHz）",
                help_text="内存工作频率，如 3200",
                null=True,
                verbose_name="内存频率（MHz）",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_total",
            field=models.PositiveIntegerField(
                db_comment="内存总量（GB）",
                default=0,
                help_text="所有内存条合计容量，单位 GB",
                verbose_name="内存总量（GB）",
            ),
        ),
        migrations.AddField(
            model_name="localserver",
            name="memory_type",
            field=models.CharField(
                blank=True,
                db_comment="内存类型",
                help_text="内存类型，如 DDR4/DDR5",
                max_length=32,
                null=True,
                verbose_name="内存类型",
            ),
        ),
        migrations.AlterField(
            model_name="localserver",
            name="disk_total",
            field=models.PositiveIntegerField(
                db_comment="磁盘总容量（GB）",
                default=0,
                help_text="所有硬盘合计容量，单位 GB",
                verbose_name="磁盘总量（GB）",
            ),
        ),
        migrations.CreateModel(
            name="DnsRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("A", "A"),
                            ("AAAA", "AAAA"),
                            ("CNAME", "CNAME"),
                            ("MX", "MX"),
                            ("TXT", "TXT"),
                            ("NS", "NS"),
                            ("SRV", "SRV"),
                            ("CAA", "CAA"),
                            ("other", "其他"),
                        ],
                        db_comment="DNS记录类型枚举值",
                        help_text="DNS 记录类型：A/AAAA/CNAME/MX/TXT/NS/SRV/CAA",
                        max_length=16,
                        verbose_name="记录类型",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        db_comment="主机记录前缀",
                        help_text="主机记录前缀，如 @、www、mail",
                        max_length=256,
                        verbose_name="主机记录",
                    ),
                ),
                (
                    "value",
                    models.TextField(
                        db_comment="解析记录值",
                        help_text="解析目标，A记录为IP、CNAME为目标域名、MX为邮件服务器地址等",
                        verbose_name="记录值",
                    ),
                ),
                (
                    "ttl",
                    models.PositiveIntegerField(
                        db_comment="TTL生存时间（秒）",
                        default=600,
                        help_text="生存时间，默认 600 秒",
                        verbose_name="TTL（秒）",
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        db_comment="MX/SRV记录优先级",
                        help_text="MX/SRV 记录的优先级，值越小优先级越高",
                        null=True,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        db_comment="启用状态：True启用/False禁用",
                        default=True,
                        help_text="解析记录是否生效",
                        verbose_name="启用状态",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "domain",
                    models.ForeignKey(
                        db_comment="归属域名ID，关联domain表",
                        help_text="该解析记录归属的域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dns_records",
                        to="asset.domain",
                        verbose_name="所属域名",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "DNS 解析记录",
                "verbose_name_plural": "DNS 解析记录",
                "db_table_comment": "域名DNS解析记录表，存储每个域名的解析配置",
                "ordering": ["domain", "record_type", "host"],
            },
        ),
    ]
