# Generated by Django 5.2.9 on 2026-07-15 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0002_hardware_and_dns"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="icp_filing_date",
            field=models.DateField(
                blank=True,
                db_comment="ICP备案日期",
                help_text="ICP 备案通过日期",
                null=True,
                verbose_name="ICP 备案日期",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="icp_number",
            field=models.CharField(
                blank=True,
                db_comment="ICP备案号",
                help_text="ICP 备案号，如 京ICP备2023000001号",
                max_length=64,
                null=True,
                verbose_name="ICP 备案号",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="ps_filing_date",
            field=models.DateField(
                blank=True,
                db_comment="公安备案日期",
                help_text="公安联网备案通过日期",
                null=True,
                verbose_name="公安备案日期",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="ps_filing_number",
            field=models.CharField(
                blank=True,
                db_comment="公安备案号",
                help_text="公安联网备案号，如 京公网安备110100000001号",
                max_length=64,
                null=True,
                verbose_name="公安备案号",
            ),
        ),
    ]
