# Generated by Django 5.2.9 on 2026-07-15 08:35

import apps.common.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0003_add_domain_filing"),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="domain_certificate",
            field=models.FileField(
                blank=True,
                db_comment="域名证书文件路径",
                help_text="域名注册证书/实名认证证书扫描件",
                null=True,
                upload_to=apps.common.core.models.upload_directory_path,
                verbose_name="域名证书",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="security_contact",
            field=models.CharField(
                blank=True,
                db_comment="安全责任人姓名",
                help_text="域名安全责任人姓名",
                max_length=64,
                null=True,
                verbose_name="安全责任人",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="security_contact_phone",
            field=models.CharField(
                blank=True,
                db_comment="安全责任人电话",
                help_text="安全责任人联系电话",
                max_length=32,
                null=True,
                verbose_name="安全责任人电话",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="service_contact",
            field=models.CharField(
                blank=True,
                db_comment="服务负责人姓名",
                help_text="域名服务/运维负责人姓名",
                max_length=64,
                null=True,
                verbose_name="服务负责人",
            ),
        ),
        migrations.AddField(
            model_name="domain",
            name="service_contact_phone",
            field=models.CharField(
                blank=True,
                db_comment="服务负责人电话",
                help_text="服务负责人联系电话",
                max_length=32,
                null=True,
                verbose_name="服务负责人电话",
            ),
        ),
    ]
