# Generated by Django 5.2.9 on 2026-07-16 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0005_add_filing_flags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="is_icp_filed",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="is_ps_filed",
        ),
    ]
