# Generated by Django 5.2.9 on 2026-07-17 08:48

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0006_remove_domain_is_icp_filed_remove_domain_is_ps_filed"),
        ("company", "0003_change_file_fields"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="domain",
            name="icp_filing_date",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="icp_number",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="ps_filing_date",
        ),
        migrations.RemoveField(
            model_name="domain",
            name="ps_filing_number",
        ),
        migrations.CreateModel(
            name="Filing",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icp_number",
                    models.CharField(
                        blank=True,
                        db_comment="ICP备案号",
                        help_text="ICP 备案号，如 京ICP备2023000001号",
                        max_length=64,
                        null=True,
                        verbose_name="ICP 备案号",
                    ),
                ),
                (
                    "icp_filing_date",
                    models.DateField(
                        blank=True,
                        db_comment="ICP备案日期",
                        help_text="ICP 备案通过日期",
                        null=True,
                        verbose_name="ICP 备案日期",
                    ),
                ),
                (
                    "icp_unit_name",
                    models.CharField(
                        blank=True,
                        db_comment="ICP备案主体名称",
                        help_text="ICP 备案主体名称（单位/个人名称）",
                        max_length=256,
                        null=True,
                        verbose_name="ICP 备案主体",
                    ),
                ),
                (
                    "icp_status",
                    models.CharField(
                        choices=[
                            ("not_filed", "未备案"),
                            ("filed", "已备案"),
                            ("pending_confirm", "待人工确认"),
                            ("changing", "变更中"),
                        ],
                        db_comment="ICP备案状态枚举值",
                        default="not_filed",
                        help_text="ICP 备案当前状态：未备案/已备案/待人工确认/变更中",
                        max_length=32,
                        verbose_name="ICP 备案状态",
                    ),
                ),
                (
                    "icp_check_status",
                    models.CharField(
                        choices=[
                            ("not_checked", "未检测"),
                            ("passed", "检测通过"),
                            ("suspected_missing", "疑似未悬挂"),
                            ("no_www_record", "无www解析"),
                            ("check_failed", "检测失败"),
                        ],
                        db_comment="ICP预检测状态枚举值",
                        default="not_checked",
                        help_text="首页悬挂备案号预检测结果",
                        max_length=32,
                        verbose_name="ICP 预检测状态",
                    ),
                ),
                (
                    "icp_has_www_record",
                    models.BooleanField(
                        db_comment="是否存在www解析记录",
                        default=False,
                        help_text="域名是否存在 www 子域名的 DNS 解析记录",
                        verbose_name="有www解析",
                    ),
                ),
                (
                    "icp_footer_content",
                    models.TextField(
                        blank=True,
                        db_comment="首页页脚文本内容",
                        help_text="首页页脚区域抓取到的文本内容（预检测时填充）",
                        null=True,
                        verbose_name="页脚内容",
                    ),
                ),
                (
                    "icp_check_conclusion",
                    models.TextField(
                        blank=True,
                        db_comment="预检测结论描述",
                        help_text="预检测的详细结论描述",
                        null=True,
                        verbose_name="检测结论",
                    ),
                ),
                (
                    "icp_check_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="最近预检测时间",
                        help_text="最近一次预检测执行时间",
                        null=True,
                        verbose_name="检测时间",
                    ),
                ),
                (
                    "ps_filing_number",
                    models.CharField(
                        blank=True,
                        db_comment="公安备案号",
                        help_text="公安联网备案号，如 京公网安备110100000001号",
                        max_length=64,
                        null=True,
                        verbose_name="公安备案号",
                    ),
                ),
                (
                    "ps_filing_date",
                    models.DateField(
                        blank=True,
                        db_comment="公安备案日期",
                        help_text="公安联网备案通过日期",
                        null=True,
                        verbose_name="公安备案日期",
                    ),
                ),
                (
                    "ps_unit_name",
                    models.CharField(
                        blank=True,
                        db_comment="公安备案主体名称",
                        help_text="公安备案主体名称",
                        max_length=256,
                        null=True,
                        verbose_name="公安备案主体",
                    ),
                ),
                (
                    "ps_public_security_agency",
                    models.CharField(
                        blank=True,
                        db_comment="备案公安机关名称",
                        help_text="受理备案的公安机关名称",
                        max_length=128,
                        null=True,
                        verbose_name="备案公安机关",
                    ),
                ),
                (
                    "ps_status",
                    models.CharField(
                        choices=[
                            ("not_filed", "未备案"),
                            ("filed", "已备案"),
                            ("pending_confirm", "待人工确认"),
                            ("changing", "变更中"),
                        ],
                        db_comment="公安备案状态枚举值",
                        default="not_filed",
                        help_text="公安备案当前状态：未备案/已备案/待人工确认",
                        max_length=32,
                        verbose_name="公安备案状态",
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        db_comment="归属公司主体ID",
                        help_text="备案主体归属的公司（冗余字段，用于筛选）",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="filings",
                        to="company.company",
                        verbose_name="所属公司",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "domain",
                    models.OneToOneField(
                        db_comment="关联域名ID，一对一",
                        help_text="该备案记录关联的域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="filing",
                        to="asset.domain",
                        verbose_name="关联域名",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "备案信息",
                "verbose_name_plural": "备案信息",
                "db_table_comment": "备案信息统一表，同时存储ICP备案与公安备案，通过 icp_*/ps_* 前缀字段区分",
                "ordering": ["-created_time"],
            },
        ),
    ]
