# Generated by Django 5.2.9 on 2026-07-20 01:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0007_remove_domain_icp_filing_date_and_more"),
        ("system", "0005_alter_datapermission_created_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SslCertificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_comment="主键ID（UUID）",
                        default=uuid.uuid4,
                        help_text="Auto-generated UUID primary key",
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_time",
                    models.DateTimeField(
                        auto_now_add=True,
                        db_comment="创建时间",
                        help_text="Timestamp automatically set when the record is first created",
                        null=True,
                        verbose_name="Created time",
                    ),
                ),
                (
                    "updated_time",
                    models.DateTimeField(
                        auto_now=True,
                        db_comment="更新时间",
                        help_text="Timestamp automatically updated each time the record is saved",
                        null=True,
                        verbose_name="Updated time",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        db_comment="描述信息",
                        help_text="Optional brief description or remark for this record",
                        max_length=256,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "subject_cn",
                    models.CharField(
                        blank=True,
                        db_comment="主体CN",
                        help_text="证书主体 Common Name，通常为域名",
                        max_length=256,
                        null=True,
                        verbose_name="主体通用名",
                    ),
                ),
                (
                    "subject_o",
                    models.CharField(
                        blank=True,
                        db_comment="主体O",
                        help_text="证书主体 Organization",
                        max_length=256,
                        null=True,
                        verbose_name="主体组织",
                    ),
                ),
                (
                    "subject_ou",
                    models.CharField(
                        blank=True,
                        db_comment="主体OU",
                        help_text="证书主体 Organizational Unit",
                        max_length=256,
                        null=True,
                        verbose_name="主体组织单元",
                    ),
                ),
                (
                    "issuer_cn",
                    models.CharField(
                        blank=True,
                        db_comment="颁发机构CN",
                        help_text="颁发机构 Common Name",
                        max_length=256,
                        null=True,
                        verbose_name="颁发机构通用名",
                    ),
                ),
                (
                    "issuer_o",
                    models.CharField(
                        blank=True,
                        db_comment="颁发机构O",
                        help_text="颁发机构 Organization",
                        max_length=256,
                        null=True,
                        verbose_name="颁发机构组织",
                    ),
                ),
                (
                    "serial_number",
                    models.CharField(
                        blank=True,
                        db_comment="证书序列号",
                        help_text="证书唯一序列号（十六进制）",
                        max_length=128,
                        null=True,
                        verbose_name="序列号",
                    ),
                ),
                (
                    "signature_algorithm",
                    models.CharField(
                        blank=True,
                        db_comment="签名算法",
                        help_text="证书签名哈希算法，如 sha256",
                        max_length=64,
                        null=True,
                        verbose_name="签名算法",
                    ),
                ),
                (
                    "not_before",
                    models.DateTimeField(
                        blank=True,
                        db_comment="证书有效期起始",
                        help_text="证书生效时间（UTC）",
                        null=True,
                        verbose_name="有效期起始",
                    ),
                ),
                (
                    "not_after",
                    models.DateTimeField(
                        blank=True,
                        db_comment="证书有效期结束",
                        help_text="证书到期时间（UTC）",
                        null=True,
                        verbose_name="有效期结束",
                    ),
                ),
                (
                    "san_domains",
                    models.JSONField(
                        blank=True,
                        db_comment="SAN域名列表",
                        default=list,
                        help_text="Subject Alternative Names 列表（证书覆盖的所有域名）",
                        verbose_name="备用域名",
                    ),
                ),
                (
                    "is_valid",
                    models.BooleanField(
                        db_comment="证书是否有效",
                        default=False,
                        help_text="检测时证书是否在有效期内",
                        verbose_name="是否有效",
                    ),
                ),
                (
                    "check_time",
                    models.DateTimeField(
                        blank=True,
                        db_comment="最近检测时间",
                        help_text="最近一次 SSL 证书检测时间",
                        null=True,
                        verbose_name="检测时间",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        blank=True,
                        db_comment="创建人",
                        help_text="User who created this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="creator_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creator",
                    ),
                ),
                (
                    "dept_belong",
                    models.ForeignKey(
                        blank=True,
                        db_comment="数据归属部门",
                        help_text="Department to which this record belongs, used for data-level permission filtering",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="dept_belong_query",
                        to="system.deptinfo",
                        verbose_name="Data ownership department",
                    ),
                ),
                (
                    "domain",
                    models.OneToOneField(
                        db_comment="关联域名ID，一对一",
                        help_text="该 SSL 证书记录关联的域名",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ssl_certificate",
                        to="asset.domain",
                        verbose_name="关联域名",
                    ),
                ),
                (
                    "modifier",
                    models.ForeignKey(
                        blank=True,
                        db_comment="修改人",
                        help_text="User who last modified this record; cleared (set to null) if the user is deleted",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        related_query_name="modifier_query",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifier",
                    ),
                ),
            ],
            options={
                "verbose_name": "SSL 证书",
                "verbose_name_plural": "SSL 证书",
                "db_table_comment": "SSL证书详细信息表，存储证书主体/颁发者/有效期/SAN等，与域名一对一",
                "ordering": ["-created_time"],
            },
        ),
    ]
