# Generated by Django 5.2.9 on 2026-07-20 01:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0008_sslcertificate"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="sslcertificate",
            table_comment="SSL证书详细信息表，相同证书（指纹去重）只存一条，被多个域名关联",
        ),
        migrations.RemoveField(
            model_name="sslcertificate",
            name="domain",
        ),
        migrations.AddField(
            model_name="domain",
            name="ssl_certificate",
            field=models.ForeignKey(
                blank=True,
                db_comment="关联SSL证书记录ID",
                help_text="关联的 SSL 证书记录，相同证书共用一条记录",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="domains",
                to="asset.sslcertificate",
                verbose_name="SSL 证书",
            ),
        ),
        migrations.AddField(
            model_name="sslcertificate",
            name="fingerprint",
            field=models.CharField(
                db_comment="SHA256指纹，唯一标识",
                default="",
                help_text="SHA256 指纹，用于判断证书是否完全一致（去重依据）",
                max_length=128,
                unique=True,
                verbose_name="证书指纹",
            ),
            preserve_default=False,
        ),
    ]
