# Generated by Django 5.2.9 on 2026-07-20 02:15

import apps.common.fields.encrypted
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asset", "0009_alter_sslcertificate_table_comment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dnsrecord",
            name="is_ssl_enabled",
            field=models.BooleanField(
                db_comment="是否支持HTTPS",
                default=False,
                help_text="该子域名是否支持 HTTPS（由 SSL 定时检测自动更新）",
                verbose_name="SSL 证书",
            ),
        ),
        migrations.AddField(
            model_name="sslcertificate",
            name="certificate_pem",
            field=models.TextField(
                blank=True,
                db_comment="终端证书PEM",
                help_text="终端证书 PEM 格式内容（自动检测填充）",
                null=True,
                verbose_name="终端证书",
            ),
        ),
        migrations.AddField(
            model_name="sslcertificate",
            name="intermediate_pem",
            field=models.TextField(
                blank=True,
                db_comment="中间证书链PEM",
                help_text="中间证书链 PEM 格式内容（自动检测填充，可能包含多张中间证书）",
                null=True,
                verbose_name="中间证书",
            ),
        ),
        migrations.AddField(
            model_name="sslcertificate",
            name="private_key_pem",
            field=apps.common.fields.encrypted.EncryptedTextField(
                blank=True,
                db_comment="私钥PEM（加密）",
                help_text="私钥 PEM 格式内容（加密存储，需手动上传，无法自动检测）",
                null=True,
                verbose_name="私钥",
            ),
        ),
    ]
